"""Exact paid source-assisted bit moment and finite stopped-leaf composition.
Physical receipts are independently regenerated by verify.py --full.
"""
if not __debug__:raise ValueError('Assertions must remain enabled')
from pathlib import Path
from fractions import Fraction as Q
import hashlib,json,sys,copy
sys.dont_write_bytecode=True;sys.set_int_max_str_digits(0)
HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[1]
PARENT=ROOT/'research/paired-cube-local-bit-168'
sys.path.insert(0,str(PARENT/'arithmetic'))
import interval_moment as im,balanced_shared,shared_bridge
raw=(HERE/'emitted-physical.json').read_bytes();source=json.loads(raw)
scalar=json.loads((HERE/'scalar-cost.json').read_text())
audit=json.loads((HERE/'independent-all-columns.json').read_text())

def validate_receipts(physical,sc,aud):
 assert physical['status']==aud['status']=='PASS'
 assert physical['word_sha256']==aud['word_sha256']
 assert physical['operations']==sc['elementary_forward_xors']==sc['elementary_inverse_xors']==aud['forward_auxiliary_operations']
 assert physical['source_controls']==sc['original_X_controls']==aud['original_source_control_operations']
 assert physical['physical_R']==aud['physical_auxiliary_roles']==aud['dirty_columns']
 assert physical['W_per_vertex']==aud['total_independent_columns']
 assert aud['source_columns']==aud['target_columns']==1760
 assert physical['W_per_vertex']==physical['physical_R']+aud['source_columns']+aud['target_columns']
 assert all(aud[k]['exact_map'] and all(aud[k][x]==0 for x in ('bad_source_rows','bad_target_rows','bad_dirty_rows')) for k in ('baseline','full_time_reverse'))
 assert all(not r['exact_map'] for r in aud['negative_controls'].values())
 assert aud['integer_lift']['exact_unit_shear_inverse_certified']
 assert not aud['integer_lift']['integer_decoder_identity_claimed']
 assert sc['payload_coefficient_alphabet']==[0,1] and sc['maximum_absolute_payload_shear_coefficient']==1
 parts=('elementary_forward_xors','elementary_inverse_xors','old_value_response_xors','root_read_xors','partner_mix_forward_inverse_xors','partner_delivery_xors')
 assert sum(sc[k] for k in parts)==sc['total_scalar_xors']==aud['literal_elementary_operations']
 assert sc['old_value_response_xors']==sc['nongauged_response_xors']+sc['gauged_response_xors']
 R=aud['logical_auxiliary_roles'];v=aud['source_columns'];M=sc['elementary_forward_xors'];h=physical['m']//3
 # Retained expanded-readout bound. With M unit updates, every defining integer
 # coefficient has magnitude <=2^M; all R*v old readouts receive M+16 bits.
 guard=4*(M+v)+10*v+4*h*v+4*h*h+8*h+8+2*h+8*R*v*(M+16)+32*v
 assert sc['total_scalar_xors']<guard
 majorants=sc['integer_non_cancelling_majorants']
 assert all(type(majorants[k])is int and 0<majorants[k]<=2**M for k in ('maximum_aux_old_read_row_l1','maximum_X_adjoint_row_l1','maximum_forward_and_inverse_row_l1'))
 assert majorants['sum_aux_old_read_row_l1']<=R*v*2**M
 return dict(local_scalar_group_upper=guard,actual_F2_unit_shears=sc['total_scalar_xors'],
   expanded_readout_bits_per_coefficient=M+16,logical_scalar_reserve=R,forward_unit_updates=M,
   integer_majorants=majorants,
   scope='Fixed local bit-word/scalar toll in the uniform recurrence. Complex precision/group bounds remain unchanged; no integer decoder identity is asserted.')
scalar_guard=validate_receipts(source,scalar,audit)
profile=dict(m=source['m'],W=source['W_per_vertex'],N=source['deficit_per_vertex'],L=0,total_rank=source['rank_per_vertex'],maxchild=max(map(int,source['child_histogram'])),child_multiplicities=source['child_histogram'])
assert profile['total_rank']==profile['m']*profile['W']-profile['N']
def paid(a):
 raw=im.moment(profile,a);ll,lu=im.log_interval(Q(profile['m']));el,eu=im.exp_interval(a*ll,a*lu)
 w=Q(1,10**16)*Q(32*profile['m']*sum(profile['child_multiplicities'].values()),profile['W'])
 return {'lower':raw['lower']+w*el,'upper':raw['upper']+w*eu}
lo=0;hi=10**16;den=10**18
assert paid(Q(lo,den))['upper']<1<paid(Q(hi,den))['lower']
while hi-lo>1:
 mid=(lo+hi)//2;m=paid(Q(mid,den))
 if m['upper']<1:lo=mid
 elif m['lower']>1:hi=mid
 else:raise ValueError('ambiguous interval')
c=Q(lo,den);accepted=paid(c);excluded=paid(Q(hi,den))
assert accepted['upper']<1<excluded['lower']
base=json.loads((PARENT/'certificate.json').read_text());old=Q(base['arithmetic']['actual_uniform_bit_saving']);chain=[old]
for j in range(3):
 a=(1-c)*c+c*chain[-1];assert chain[-1]<a<c<1-a;chain.append(a)
assert chain[-1]==c-c**3*(c-old)
row=base['complex']['profile'];legacy_uniform=copy.deepcopy(base['arithmetic']['bridge']['bit_uniform'])
bridge=copy.deepcopy(base['arithmetic']['bridge']);bridge['bit_uniform'].update(coarse_saving=c,atom_beta=c,old_atom_saving=chain[-2],ordinary_saving=chain[-1])
def validation(new,complex_row):
 u=new['bit_uniform']
 for k,expected in [('coarse_saving',c),('atom_beta',c),('old_atom_saving',chain[-2]),('ordinary_saving',chain[-1])]:
  assert Q(u[k])==expected,('stale substituted quantity',k)
 legacy=copy.deepcopy(new);legacy['bit_uniform']=copy.deepcopy(legacy_uniform)
 checked=shared_bridge.validate_shared_bridge(legacy,complex_row)
 checked['bit_uniform']={k:Q(u[k]) for k in ('coarse_saving','atom_beta','old_atom_saving','ordinary_saving')}
 return checked
balanced_shared.validate_shared_bridge=validation
beta=eta=Q(1,10**24);weakening=Q(1,10**30);b=Q(base['arithmetic']['complex_saving']);a=min(chain[-1],(1-beta)*b-weakening)
assert a==(1-beta)*b-weakening
q=a*(1-2*eta);ceiling=(1-eta)*q/(1+q);z=ceiling*den;kappa=Q((z.numerator-1)//z.denominator,den)
assembly=balanced_shared.assembly(bridge,row,a,kappa,beta=beta,h=eta,a_complex=b)
assert len(assembly['constraints'])==47 and len(assembly['margins'])==7
assert min(map(Q,assembly['constraints'].values()))>0
assert min(map(Q,assembly['margins'].values()))>kappa
controls=[]
def reject(name,fun):
 try:fun()
 except (ValueError,AssertionError,KeyError):controls.append(name)
 else:raise AssertionError('accepted '+name)
reject('next final grid',lambda:balanced_shared.assembly(bridge,row,a,kappa+Q(1,den),beta=beta,h=eta,a_complex=b))
reject('complex supplier overstated',lambda:balanced_shared.assembly(bridge,row,b,kappa,beta=beta,h=eta,a_complex=b))
reject('bit supplier overstated',lambda:balanced_shared.assembly(bridge,row,chain[-1]+Q(1,den),kappa,beta=beta,h=eta,a_complex=b))
bad=copy.deepcopy(profile);bad['total_rank']+=1;reject('rank mass changed',lambda:im.moment(bad,c))
assert Q(2*profile['m']**3,2**80)<Q(1,10**16)
assert profile['total_rank']+Q(1,10**16)*32*profile['m']**2*sum(profile['child_multiplicities'].values())<profile['m']*profile['W']
def js(x):
 if isinstance(x,Q):return str(x)
 if isinstance(x,dict):return {str(k):js(v) for k,v in x.items()}
 if isinstance(x,(list,tuple)):return [js(v) for v in x]
 return x
out=dict(status='PASS conditional finite source-assisted bit supplier and assembly',
 source_sha256={name:hashlib.sha256((HERE/name).read_bytes()).hexdigest() for name in ('emitted-physical.json','scalar-cost.json','independent-all-columns.json')},
 profile=profile,word_sha256=source['word_sha256'],scalar_guard=scalar_guard,
 profile_origin='Actual newly emitted elementary-word physical histogram; independently replayed source/target/dirty columns',
 coarse=c,accepted=accepted,next_coarse_excluded=excluded,ordinary_chain=chain,atom_exponent=c,transfer_saving=a,complex_saving=b,
 kappa=kappa,improvement_over185=kappa/Q(660627334074291,10**18)-1,assembly=assembly,controls_rejected=controls,
 source_interface_obligations=['Retained general weighted compiler and all-size ordinary supplier','Finite-frame good-prime selection','Completed ordinary spectator and restored-row contract','Analytic and fixed-tape composition'],
 scope='New bit scalar/geometry receipts are rederived by verify.py --full. Exact finite arithmetic preserves the conditional framework; F2 endpoint correctness is distinct from signed integer inverse and coefficient bounds.')
# Additional receipt/control failures must not silently become certified inputs.
def mutate_receipt(name,which,key,value):
 a,b,c=copy.deepcopy(source),copy.deepcopy(scalar),copy.deepcopy(audit)
 {'physical':a,'scalar':b,'audit':c}[which][key]=value
 reject(name,lambda:validate_receipts(a,b,c))
mutate_receipt('changed word digest','physical','word_sha256','0'*64)
mutate_receipt('omitted scalar work','scalar','total_scalar_xors',scalar['total_scalar_xors']-1)
mutate_receipt('missing dirty column','audit','dirty_columns',audit['dirty_columns']-1)
mutate_receipt('false integer decoder claim','audit','integer_lift',dict(audit['integer_lift'],integer_decoder_identity_claimed=True))
out['controls_rejected']=controls
actual=js(out)
if __name__=='__main__':
 if not __debug__:raise ValueError('Assertions must remain enabled')
 if '--write' in sys.argv:
  (HERE/'certificate.json').write_text(json.dumps(actual,indent=2)+'\n')
 else:
  assert actual==json.loads((HERE/'certificate.json').read_text()),'Canonical arithmetic certificate differs'
  print('PASS actual emitted histogram and scalar guard; exact paid moments; finite leaf bootstrap; 47 constraints,7 margins,8 controls andadjacentgrids')
  print('kappa='+actual['kappa'])
